"""Magellan-style entity resolution pipeline using scikit-learn Random Forest."""

import logging
import time
import random
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from src.pipelines.magellan.features import FEATURE_NAMES, compute_features_for_pairs
from src.pipelines.magellan.tuning import load_best_params
from src.utils import build_product_lookup, build_label_series

logger = logging.getLogger(__name__)

DEFAULT_RF_PARAMS = {
  "n_estimators": 50,
  "max_depth": None,
  "min_samples_split": 2,
  "max_features": "sqrt",
  "class_weight": "balanced",
}


def _print_debug_info(
  X: np.ndarray,
  y: np.ndarray,
  pair_ids: list[tuple[str, str]],
  rf: RandomForestClassifier,
  src_lookup: dict,
  tgt_lookup: dict,
) -> None:
  """Print debug information about features, sample data, and model."""
  print("\n" + "-" * 50)
  print("Debug Info: Magellan Pipeline")
  print("-" * 50)

  # Feature names
  print(f"\nFeatures ({len(FEATURE_NAMES)}):")
  for i, name in enumerate(FEATURE_NAMES):
    print(f"  [{i:2d}] {name}")

  # Feature statistics
  print(f"\nTraining matrix shape: {X.shape}")
  print(f"Label distribution: {int(y.sum())} positive, {int(len(y) - y.sum())} negative")
  print("\nFeature statistics (training set):")
  print(f"  {'Feature':<25s} {'min':>8s} {'max':>8s} {'mean':>8s} {'std':>8s}")
  print(f"  {'-'*25} {'-'*8} {'-'*8} {'-'*8} {'-'*8}")
  for i, name in enumerate(FEATURE_NAMES):
    col = X[:, i]
    print(f"  {name:<25s} {col.min():8.3f} {col.max():8.3f} {col.mean():8.3f} {col.std():8.3f}")

  # Sample pairs (5 random)
  n_samples = min(5, len(pair_ids))
  sample_indices = random.sample(range(len(pair_ids)), n_samples)
  print(f"\nSample pairs ({n_samples} random):")
  for i, idx in enumerate(sample_indices):
    src_id, tgt_id = pair_ids[idx]
    src = src_lookup.get(src_id, {})
    tgt = tgt_lookup.get(tgt_id, {})
    label = "MATCH" if y[idx] == 1 else "NO MATCH"
    print(f"\n  Pair {idx + 1} [{label}]: ({src_id}, {tgt_id})")
    print(f"    Source: name={src.get('name', '?')!r}, price={src.get('price', '?')}")
    print(f"    Target: name={tgt.get('name', '?')!r}, price={tgt.get('price', '?')}")
    print(f"    Features: {', '.join(f'{FEATURE_NAMES[j]}={X[idx, j]:.3f}' for j in range(len(FEATURE_NAMES)))}")

  # Feature importances
  print("\nFeature importances (Random Forest):")
  importances = rf.feature_importances_
  sorted_idx = np.argsort(importances)[::-1]
  for rank, idx in enumerate(sorted_idx):
    print(f"  {rank + 1:2d}. {FEATURE_NAMES[idx]:<25s} {importances[idx]:.4f}")

  print("-" * 50 + "\n")


def run_magellan_pipeline(
  candidate_pairs: pd.DataFrame,
  source_df: pd.DataFrame,
  target_df: pd.DataFrame,
  train_pairs_df: pd.DataFrame,
  valid_pairs_df: pd.DataFrame,
  max_pairs: int | None = None,
  debug: bool = False,
  random_state: int = 77,
) -> tuple[list[dict], int, float]:
  """
  Run Magellan-style entity resolution using a Random Forest classifier.

  Loads pre-tuned hyperparameters from data/magellan_best_params.json
  (generated by tuning.py). Falls back to defaults if not found.
  Trains on train + valid splits, predicts on blocked candidates.

  Args:
    candidate_pairs: Blocked candidate pairs (source_id, target_id, ...).
    source_df: Source product table with id, name, description, price.
    target_df: Target product table with id, name, description, price.
    train_pairs_df: Labeled training pairs (ltable_id, rtable_id, label).
    valid_pairs_df: Labeled validation pairs (ltable_id, rtable_id, label).
    max_pairs: If set, only predict on the first N candidate pairs.
    debug: If True, print feature names, statistics, sample data, and importances.

  Returns:
    Tuple of (predictions list, total_tokens=0, elapsed_seconds).
  """
  start_time = time.time()

  # Load tuned params or use defaults
  rf_params, threshold = load_best_params()
  if rf_params:
    logger.info("Loaded tuned RF params: %s (threshold=%.2f)", rf_params, threshold)
  else:
    rf_params = DEFAULT_RF_PARAMS
    threshold = 0.5
    logger.info("No tuned params found. Using defaults: %s", rf_params)

  src_lookup = build_product_lookup(source_df)
  tgt_lookup = build_product_lookup(target_df)

  # Featurize train + valid together for final training
  combined_pairs = pd.concat([train_pairs_df, valid_pairs_df], ignore_index=True)
  combined_renamed = combined_pairs.rename(
    columns={"ltable_id": "source_id", "rtable_id": "target_id"}
  )

  logger.info("Computing training features for %d pairs...", len(combined_renamed))
  X_train, train_pair_ids = compute_features_for_pairs(combined_renamed, src_lookup, tgt_lookup)

  if len(X_train) == 0:
    raise RuntimeError("No features could be generated for training pairs. Check data and feature functions.")

  label_lookup = build_label_series(combined_pairs)
  y_train = np.array([label_lookup.get(pid, 0) for pid in train_pair_ids])

  n_positive = int(y_train.sum())
  logger.info(
    "Training data: %d pairs, %d positive, %d negative",
    len(y_train), n_positive, len(y_train) - n_positive,
  )

  # Train Random Forest
  rf = RandomForestClassifier(random_state=random_state, n_jobs=-1, **rf_params)
  rf.fit(X_train, y_train)
  logger.info("Random Forest trained.")

  # If no pre-tuned threshold, find one using validation set.
  # Extract train-only and valid subsets from the already-computed combined matrix
  # (combined_pairs = [train, valid] so pair_ids preserve that order).
  if threshold == 0.5:
    from src.pipelines.magellan.tuning import find_best_threshold
    train_label_lookup = build_label_series(train_pairs_df)
    valid_label_lookup = build_label_series(valid_pairs_df)
    train_only_mask = [pid in train_label_lookup for pid in train_pair_ids]
    valid_mask = [pid in valid_label_lookup for pid in train_pair_ids]
    X_train_only = X_train[train_only_mask]
    X_val = X_train[valid_mask]
    y_train_only = y_train[train_only_mask]
    y_val = np.array([valid_label_lookup.get(pid, 0) for pid in train_pair_ids if pid in valid_label_lookup])
    if len(X_val) > 0 and len(X_train_only) > 0:
      temp_rf = RandomForestClassifier(random_state=random_state, n_jobs=-1, **rf_params)
      temp_rf.fit(X_train_only, y_train_only)
      if 1 in temp_rf.classes_:
        val_proba = temp_rf.predict_proba(X_val)[:, list(temp_rf.classes_).index(1)]
        threshold, val_f1 = find_best_threshold(y_val, val_proba)
        logger.info("Auto-tuned threshold: %.2f (valid F1=%.4f)", threshold, val_f1)

  if debug:
    _print_debug_info(X_train, y_train, train_pair_ids, rf, src_lookup, tgt_lookup)

  # Predict on candidate pairs
  pairs = candidate_pairs.head(max_pairs) if max_pairs else candidate_pairs
  logger.info("Computing candidate features for %d pairs...", len(pairs))
  X_cand, cand_pair_ids = compute_features_for_pairs(pairs, src_lookup, tgt_lookup)

  if len(X_cand) == 0:
    return [], 0, time.time() - start_time

  y_proba = (
    rf.predict_proba(X_cand)[:, list(rf.classes_).index(1)]
    if 1 in rf.classes_
    else np.zeros(len(X_cand))
  )
  y_pred = (y_proba >= threshold).astype(int)

  predictions: list[dict] = []
  for (src_id, tgt_id), pred, proba in zip(cand_pair_ids, y_pred, y_proba):
    predictions.append({
      "source_id": src_id,
      "target_id": tgt_id,
      "verdict": "MATCH" if pred == 1 else "NO MATCH",
      "confidence": float(proba),
      "parse_error": False,
    })

  elapsed = time.time() - start_time
  logger.info(
    "Magellan pipeline done: %d predictions in %.1fs", len(predictions), elapsed,
  )

  return predictions, 0, elapsed
